/** Auto-generated by import-gonad-auxology-data.mjs — run npm run import:data */

export const GONAD_AUXOLOGY_CACHE_BUST = "1783993772904.4944";

/** Public URLs for gonad auxology reference charts (2/2 copied). */
export const GONAD_AUXOLOGY_CHART_URLS = {
  usaSchonfeld: "/gonad-auxology/SPL-USA-SCHONFELD.png?v=1783993772904.4944",
  usaFeldman: "/gonad-auxology/SPL-child-USA-feldman.jpg?v=1783993772904.4944",
} as const;
