/** Auto-generated by import-clinical-data.mjs — run npm run import:data */

export const CAH_CACHE_BUST = "1783194234118.4102";

/** Public URLs for CAH nomogram PNGs (3/3 copied). */
export const CAH_CHART_URLS = {
  cah2003: "/cah/CAH-2003.png?v=1783194234118.4102",
  cah2018: "/cah/CAH-2018.png?v=1783194234118.4102",
  cah2018Israel: "/cah/CAH-2018-Israel.png?v=1783194234118.4102",
} as const;
