/** Auto-generated by scripts/import-tw3-individual-stages.mjs — run npm run import:data */
import type { Tw3LandmarkId, Tw3MaturityRating } from "../../core/calculators/tw3/types";
import { ATLAS_CACHE_BUST } from "./atlasVersion";

export interface Tw3StageImageEntry {
  rating: Tw3MaturityRating;
  referenceSrc: string;
  descriptionLines: string[];
}

function stageImageUrl(fileName: string): string {
  return `/atlas/individual-stages/${encodeURI(fileName)}?v=${ATLAS_CACHE_BUST}`;
}

type RawStageRow = {
  rating: Tw3MaturityRating;
  imageFile: string;
  descriptionLines: string[];
};

const RAW_STAGE_MANIFEST: Record<Tw3LandmarkId, RawStageRow[]> = {
  "radius": [
    {
      "rating": "B",
      "imageFile": "rad_img_B.png",
      "descriptionLines": [
        "(i) The centre is just visible as a single deposit of calcium, or more rarely as multiple deposits. The border is ill-defined."
      ]
    },
    {
      "rating": "C",
      "imageFile": "rad_img_C.png",
      "descriptionLines": [
        "(i) The centre is distinct in appearance and oval in shape, with a smooth, continuous border."
      ]
    },
    {
      "rating": "D",
      "imageFile": "rad_img_D.png",
      "descriptionLines": [
        "(i) The maximum diameter is half or more the width of the metaphysis.",
        "(ii) The epiphysis has broadened chiefly at its lateral side, so that this portion is thicker and more rounded, the medial portion more tapering.",
        "(iii) The centre third of the proximal surface is flat and slightly thickened and the gap between it and the radial metaphysis has narrowed to about a millimetre."
      ]
    },
    {
      "rating": "E",
      "imageFile": "rad_img_E.png",
      "descriptionLines": [
        "(i) A thickened white line has appeared just inside the distal border of the epiphysis; this represents the edge of the palmar surface and the newly appeared bone distal to it is the edge of the dorsal surface."
      ]
    },
    {
      "rating": "F",
      "imageFile": "rad_img_F.png",
      "descriptionLines": [
        "(i) The proximal border of the epiphysis is now differentiated into palmar and dorsal surfaces; the palmar surface is visible as a broad, irregularly thickened white line at the proximal edge of the epiphysis.",
        "(ii) Both ends of the epiphysis, but particularly the medial one, have grown outwards and proximally since the last stage so that the proximal border now conforms to the shape of the metaphysis along most of its extent."
      ]
    },
    {
      "rating": "G",
      "imageFile": "rad_img_G.png",
      "descriptionLines": [
        "(i) The dorsal surface now has distinct lunate and scaphoid articular edges joined at a small hump.",
        "(ii) The medial border of the epiphysis has developed palmar and dorsal surfaces for articulation with the ulnar epiphysis; either the palmar or the dorsal surface may be the one that projects medially, depending on the position of the wrist.",
        "(iii) The proximal border of the epiphysis is now slightly concave."
      ]
    },
    {
      "rating": "H",
      "imageFile": "rad_img_H.png",
      "descriptionLines": [
        "(i) The epiphysis now caps the metaphysis on one (usually the medial) or both sides."
      ]
    },
    {
      "rating": "I",
      "imageFile": "rad_img_I.png",
      "descriptionLines": [
        "(i) Fusion of the epiphysis and metaphysis has begun. A line may still be visible, composed partly of black areas where the epiphyseal cartilage remains and partly of dense white areas where fusion is proceeding; or the line may have disappeared."
      ]
    }
  ],
  "ulna": [
    {
      "rating": "B",
      "imageFile": "uln_img_B.png",
      "descriptionLines": [
        "(i) The centre is just visible as a single deposit of calcium, or more rarely as multiple deposits. The border is ill-defined."
      ]
    },
    {
      "rating": "C",
      "imageFile": "uln_img_C.png",
      "descriptionLines": [
        "(i) The centre is distinct in appearance, with a smooth, continuous border."
      ]
    },
    {
      "rating": "D",
      "imageFile": "uln_img_D.png",
      "descriptionLines": [
        "(i) The maximum diameter is half or more the width of the metaphysis.",
        "(ii) The epiphysis is now elongated so that the transverse, mediolateral diameter is considerably greater than the longitudinal, distoproximal diameter.",
        "(iii) Proximal and distal borders are both flattened, though not necessarily parallel, so that the epiphysis is usually wedge-shaped with the point facing laterally."
      ]
    },
    {
      "rating": "E",
      "imageFile": "uln_img_E.png",
      "descriptionLines": [
        "(i) The styloid process is now visible as a distinct though small projection."
      ]
    },
    {
      "rating": "F",
      "imageFile": "uln_img_F.png",
      "descriptionLines": [
        "(i) The head of the ulna is now distinctly defined and denser than the styloid process. (Its medial surface usually appears as a thickened white line differentiating it from the styloid process, and there is often a concavity of the proximal and/or distal border of the epiphysis where the head and styloid meet.)",
        "(ii) The border adjacent to the radial epiphysis is flattened."
      ]
    },
    {
      "rating": "G",
      "imageFile": "uln_img_G.png",
      "descriptionLines": [
        "(i) The epiphysis is now as wide as the metaphysis.",
        "(ii) The proximal border of the epiphysis and the distal border of the metaphysis overlap in their central one-third."
      ]
    },
    {
      "rating": "H",
      "imageFile": "uln_img_H.png",
      "descriptionLines": [
        "(i) Fusion of epiphysis and metaphysis has begun. The line between epiphysis and metaphysis may be still visible, composed partly of black areas, usually on the styloid side, where the epiphyseal cartilage remains, and partly of dense white areas where fusion is proceeding; or the line may have disappeared."
      ]
    }
  ],
  "metacarpal_1": [
    {
      "rating": "B",
      "imageFile": "1MC_img_B.png",
      "descriptionLines": [
        "(i) The centre is just visible as a single deposit of calcium, or more rarely as multiple deposits. The border is ill-defined."
      ]
    },
    {
      "rating": "C",
      "imageFile": "1MC_img_C.png",
      "descriptionLines": [
        "(i) The epiphysis is distinct in appearance and oval in shape, with a smooth, continuous border."
      ]
    },
    {
      "rating": "D",
      "imageFile": "1MC_img_D.png",
      "descriptionLines": [
        "(i) The maximum diameter is half or more the width of the metaphysis."
      ]
    },
    {
      "rating": "E",
      "imageFile": "1MC_img_E.png",
      "descriptionLines": [
        "(i) The epiphysis is as wide as the metaphysis.",
        "(ii) A concavity is present in the proximal border. (This is due to the first appearance of palmar and dorsal surfaces of the epiphysis, though as yet these surfaces themselves are not distinct.)"
      ]
    },
    {
      "rating": "F",
      "imageFile": "1MC_img_F.png",
      "descriptionLines": [
        "(i) The differentiation of the proximal surface into palmar and dorsal portions is now distinct and the full extent of the dorsal surface can be made out; owing to the rotation of the thumb in its position on the film, these surfaces appear as laterodorsal and mediopalmar. The saddle formed by these surfaces conforms to the adjacent border of the trapezium bone. (Towards the end of this stage the medial border of the epiphysis changes from a rounded shape to a flat, distinct border.)"
      ]
    },
    {
      "rating": "G",
      "imageFile": "1MC_img_G.png",
      "descriptionLines": [
        "(i) The epiphysis caps the metaphysis on one or both sides; the capping is usually seen better on the medial than on the lateral side, owing to the rotation of the thumb in positioning the hand."
      ]
    },
    {
      "rating": "H",
      "imageFile": "1MC_img_H.png",
      "descriptionLines": [
        "(i) Fusion of the epiphysis and metaphysis has begun. A line is still visible, composed partly of black areas where the epiphyseal cartilage remains and partly of dense white areas where fusion has occurred."
      ]
    },
    {
      "rating": "I",
      "imageFile": "1MC_img_I.png",
      "descriptionLines": [
        "(i) Fusion of the epiphysis and metaphysis is completed. (Over the majority of its length the line of fusion has entirely disappeared, but some thickened remnant of it may still be visible.)"
      ]
    }
  ],
  "metacarpal_3": [
    {
      "rating": "B",
      "imageFile": "35MC_img_B.png",
      "descriptionLines": [
        "(i) The centre is just visible as a single deposit of calcium, or more rarely as multiple deposits. The border is ill-defined."
      ]
    },
    {
      "rating": "C",
      "imageFile": "35MC_img_C.png",
      "descriptionLines": [
        "(i) The epiphysis is distinct in appearance and rounded in shape, with a smooth, continuous border."
      ]
    },
    {
      "rating": "D",
      "imageFile": "35MC_img_D.png",
      "descriptionLines": [
        "(i) The transverse diameter is half or more the width of the metaphysis."
      ]
    },
    {
      "rating": "E",
      "imageFile": "35MC_img_E.png",
      "descriptionLines": [
        "(i) Since the preceding stage the shape of the epiphysis has changed from being an oval or semicircle to that of a spade or fingernail. This occurs by virtue of the lateral, medial and proximal borders of the epiphysis becoming distinct one from another, and identifiable by the angles seen at their junctions."
      ]
    },
    {
      "rating": "F",
      "imageFile": "35MC_img_F.png",
      "descriptionLines": [
        "(i) It is now possible, in a good film, to distinguish the palmar from the dorsal surface of the epiphysis. Since the last stage the medial and/or lateral edges of the dorsal surface have grown outwards to overlap the palmar surface of the epiphysis. The outlines of the palmar edges now appear as longitudinal, thickened white lines."
      ]
    },
    {
      "rating": "G",
      "imageFile": "35MC_img_G.png",
      "descriptionLines": [
        "(i) The epiphysis is as wide as, or wider than, the metaphysis. (This stage would seem to be the equivalent of the stage of capping in the epiphysis of the phalanges.)"
      ]
    },
    {
      "rating": "H",
      "imageFile": "35MC_img_H.png",
      "descriptionLines": [
        "(i) Fusion of the epiphysis and metaphysis has begun. The dark line of cartilage extends over less than three-quarters of the bone's breadth, but is not entirely obliterated."
      ]
    },
    {
      "rating": "I",
      "imageFile": "35MC_img_I.png",
      "descriptionLines": [
        "(i) Fusion of the epiphysis and metaphysis is completed. (Over the majority of its length the line of fusion has entirely disappeared, but some thickened remnant of it may still be visible.)"
      ]
    }
  ],
  "metacarpal_5": [
    {
      "rating": "B",
      "imageFile": "35MC_img_B.png",
      "descriptionLines": [
        "(i) The centre is just visible as a single deposit of calcium, or more rarely as multiple deposits. The border is ill-defined."
      ]
    },
    {
      "rating": "C",
      "imageFile": "35MC_img_C.png",
      "descriptionLines": [
        "(i) The epiphysis is distinct in appearance and rounded in shape, with a smooth, continuous border."
      ]
    },
    {
      "rating": "D",
      "imageFile": "35MC_img_D.png",
      "descriptionLines": [
        "(i) The transverse diameter is half or more the width of the metaphysis."
      ]
    },
    {
      "rating": "E",
      "imageFile": "35MC_img_E.png",
      "descriptionLines": [
        "(i) Since the preceding stage the shape of the epiphysis has changed from being an oval or semicircle to that of a spade or fingernail. This occurs by virtue of the lateral, medial and proximal borders of the epiphysis becoming distinct one from another, and identifiable by the angles seen at their junctions."
      ]
    },
    {
      "rating": "F",
      "imageFile": "35MC_img_F.png",
      "descriptionLines": [
        "(i) It is now possible, in a good film, to distinguish the palmar from the dorsal surface of the epiphysis. Since the last stage the medial and/or lateral edges of the dorsal surface have grown outwards to overlap the palmar surface of the epiphysis. The outlines of the palmar edges now appear as longitudinal, thickened white lines."
      ]
    },
    {
      "rating": "G",
      "imageFile": "35MC_img_G.png",
      "descriptionLines": [
        "(i) The epiphysis is as wide as, or wider than, the metaphysis. (This stage would seem to be the equivalent of the stage of capping in the epiphysis of the phalanges.)"
      ]
    },
    {
      "rating": "H",
      "imageFile": "35MC_img_H.png",
      "descriptionLines": [
        "(i) Fusion of the epiphysis and metaphysis has begun. The dark line of cartilage extends over less than three-quarters of the bone's breadth, but is not entirely obliterated."
      ]
    },
    {
      "rating": "I",
      "imageFile": "35MC_img_I.png",
      "descriptionLines": [
        "(i) Fusion of the epiphysis and metaphysis is completed. (Over the majority of its length the line of fusion has entirely disappeared, but some thickened remnant of it may still be visible.)"
      ]
    }
  ],
  "proximal_phalanx_1": [
    {
      "rating": "B",
      "imageFile": "1PP_img_B.png",
      "descriptionLines": [
        "(i) The centre is just visible as a single deposit of calcium or more rarely as multiple deposits. The border is ill-defined."
      ]
    },
    {
      "rating": "C",
      "imageFile": "1PP_img_C.png",
      "descriptionLines": [
        "(i) The centre is distinct in appearance and disc-shaped, with a smooth, continuous border. (Multiple centres may occur whose summed maximum diameters exceed half the width of the metaphysis; they should, however, be rated stage C.)"
      ]
    },
    {
      "rating": "D",
      "imageFile": "1PP_img_D.png",
      "descriptionLines": [
        "(i) The maximum diameter is half or more the width of the metaphysis."
      ]
    },
    {
      "rating": "E",
      "imageFile": "1PP_img_E.png",
      "descriptionLines": [
        "(i) The proximal border is concave and usually thickened.",
        "(ii) The medial side is longer than the lateral, giving a wedge-shaped appearance."
      ]
    },
    {
      "rating": "F",
      "imageFile": "1PP_img_F.png",
      "descriptionLines": [
        "(i) The epiphysis is wider than the metaphysis, particularly at the medial side, and closely follows its shape."
      ]
    },
    {
      "rating": "G",
      "imageFile": "1PP_img_G.png",
      "descriptionLines": [
        "(i) The epiphysis caps the metaphysis. (The capping is seen better on the medial than on the lateral side.)"
      ]
    },
    {
      "rating": "H",
      "imageFile": "1PP_img_H.png",
      "descriptionLines": [
        "(i) Fusion of the epiphysis and metaphysis has begun."
      ]
    },
    {
      "rating": "I",
      "imageFile": "1PP_img_I.png",
      "descriptionLines": [
        "(i) Fusion of the epiphysis and metaphysis is completed. (Over the majority of its length the line of fusion has entirely disappeared, but some thickened remnant of it may still be visible.)"
      ]
    }
  ],
  "proximal_phalanx_3": [
    {
      "rating": "B",
      "imageFile": "35PP_img_B.png",
      "descriptionLines": [
        "(i) The centre is just visible as a single deposit of calcium, or more rarely as multiple deposits. The border is ill-defined."
      ]
    },
    {
      "rating": "C",
      "imageFile": "35PP_img_C.png",
      "descriptionLines": [
        "(i) The centre is distinct in appearance and disc-shaped, with a smooth, continuous border."
      ]
    },
    {
      "rating": "D",
      "imageFile": "35PP_img_D.png",
      "descriptionLines": [
        "(i) The epiphysis is half or more the width of the metaphysis."
      ]
    },
    {
      "rating": "E",
      "imageFile": "35PP_img_E.png",
      "descriptionLines": [
        "(i) The proximal border of the epiphysis is concave and distinctly thickened."
      ]
    },
    {
      "rating": "F",
      "imageFile": "35PP_img_F.png",
      "descriptionLines": [
        "(i) The epiphysis is as wide as the metaphysis and closely follows its shape, although it does not yet cap it at the edges."
      ]
    },
    {
      "rating": "G",
      "imageFile": "35PP_img_G.png",
      "descriptionLines": [
        "(i) The epiphysis caps the metaphysis."
      ]
    },
    {
      "rating": "H",
      "imageFile": "35PP_img_H.png",
      "descriptionLines": [
        "(i) Fusion of the epiphysis and metaphysis has now begun. A line is still visible, composed partly of black areas where the epiphyseal cartilage remains and partly of dense white areas where fusion is proceeding."
      ]
    },
    {
      "rating": "I",
      "imageFile": "35PP_img_I.png",
      "descriptionLines": [
        "(i) Fusion of the epiphysis and metaphysis is completed. (Over the majority of its length the line of fusion has entirely disappeared, but some thickened remnant of it may still be visible.)"
      ]
    }
  ],
  "proximal_phalanx_5": [
    {
      "rating": "B",
      "imageFile": "35PP_img_B.png",
      "descriptionLines": [
        "(i) The centre is just visible as a single deposit of calcium, or more rarely as multiple deposits. The border is ill-defined."
      ]
    },
    {
      "rating": "C",
      "imageFile": "35PP_img_C.png",
      "descriptionLines": [
        "(i) The centre is distinct in appearance and disc-shaped, with a smooth, continuous border."
      ]
    },
    {
      "rating": "D",
      "imageFile": "35PP_img_D.png",
      "descriptionLines": [
        "(i) The epiphysis is half or more the width of the metaphysis."
      ]
    },
    {
      "rating": "E",
      "imageFile": "35PP_img_E.png",
      "descriptionLines": [
        "(i) The proximal border of the epiphysis is concave and distinctly thickened."
      ]
    },
    {
      "rating": "F",
      "imageFile": "35PP_img_F.png",
      "descriptionLines": [
        "(i) The epiphysis is as wide as the metaphysis and closely follows its shape, although it does not yet cap it at the edges."
      ]
    },
    {
      "rating": "G",
      "imageFile": "35PP_img_G.png",
      "descriptionLines": [
        "(i) The epiphysis caps the metaphysis."
      ]
    },
    {
      "rating": "H",
      "imageFile": "35PP_img_H.png",
      "descriptionLines": [
        "(i) Fusion of the epiphysis and metaphysis has now begun. A line is still visible, composed partly of black areas where the epiphyseal cartilage remains and partly of dense white areas where fusion is proceeding."
      ]
    },
    {
      "rating": "I",
      "imageFile": "35PP_img_I.png",
      "descriptionLines": [
        "(i) Fusion of the epiphysis and metaphysis is completed. (Over the majority of its length the line of fusion has entirely disappeared, but some thickened remnant of it may still be visible.)"
      ]
    }
  ],
  "middle_phalanx_3": [
    {
      "rating": "B",
      "imageFile": "35MP_img_B.png",
      "descriptionLines": [
        "(i) The centre is just visible as a single deposit of calcium, or more rarely as multiple deposits. The border is ill-defined."
      ]
    },
    {
      "rating": "C",
      "imageFile": "35MP_img_C.png",
      "descriptionLines": [
        "(i) The centre is distinct in appearance and disc-shaped, with a smooth, continuous border."
      ]
    },
    {
      "rating": "D",
      "imageFile": "35MP_img_D.png",
      "descriptionLines": [
        "(i) The maximum diameter is half or more the width of the metaphysis."
      ]
    },
    {
      "rating": "E",
      "imageFile": "35MP_img_E.png",
      "descriptionLines": [
        "(i) The central portion of the proximal border has thickened and grown towards the end of the adjacent phalanx, shaping to its trochlear surface. (This thickened white line represents the dorsal surface of the epiphysis; proximal to it the palmar surface is usually visible on one or both sides as a convex projection. In some positions of the hand, however, these proximal edges of palmar and dorsal surfaces appear superimposed.)"
      ]
    },
    {
      "rating": "F",
      "imageFile": "35MP_img_F.png",
      "descriptionLines": [
        "(i) The epiphysis is as wide as the metaphysis."
      ]
    },
    {
      "rating": "G",
      "imageFile": "35MP_img_G.png",
      "descriptionLines": [
        "(i) The epiphysis caps the metaphysis."
      ]
    },
    {
      "rating": "H",
      "imageFile": "35MP_img_H.png",
      "descriptionLines": [
        "(i) Fusion of epiphysis and metaphysis has begun. A line is still visible, composed partly of black areas where the epiphyseal cartilage remains and partly of dense white areas where fusion is proceeding."
      ]
    },
    {
      "rating": "I",
      "imageFile": "35MP_img_I.png",
      "descriptionLines": [
        "(i) Fusion of the epiphysis and metaphysis is completed. (Over the majority of its length the line of fusion has entirely disappeared, but some thickened remnant of it may still be visible.)"
      ]
    }
  ],
  "middle_phalanx_5": [
    {
      "rating": "B",
      "imageFile": "35MP_img_B.png",
      "descriptionLines": [
        "(i) The centre is just visible as a single deposit of calcium, or more rarely as multiple deposits. The border is ill-defined."
      ]
    },
    {
      "rating": "C",
      "imageFile": "35MP_img_C.png",
      "descriptionLines": [
        "(i) The centre is distinct in appearance and disc-shaped, with a smooth, continuous border."
      ]
    },
    {
      "rating": "D",
      "imageFile": "35MP_img_D.png",
      "descriptionLines": [
        "(i) The maximum diameter is half or more the width of the metaphysis."
      ]
    },
    {
      "rating": "E",
      "imageFile": "35MP_img_E.png",
      "descriptionLines": [
        "(i) The central portion of the proximal border has thickened and grown towards the end of the adjacent phalanx, shaping to its trochlear surface. (This thickened white line represents the dorsal surface of the epiphysis; proximal to it the palmar surface is usually visible on one or both sides as a convex projection. In some positions of the hand, however, these proximal edges of palmar and dorsal surfaces appear superimposed.)"
      ]
    },
    {
      "rating": "F",
      "imageFile": "35MP_img_F.png",
      "descriptionLines": [
        "(i) The epiphysis is as wide as the metaphysis."
      ]
    },
    {
      "rating": "G",
      "imageFile": "35MP_img_G.png",
      "descriptionLines": [
        "(i) The epiphysis caps the metaphysis."
      ]
    },
    {
      "rating": "H",
      "imageFile": "35MP_img_H.png",
      "descriptionLines": [
        "(i) Fusion of epiphysis and metaphysis has begun. A line is still visible, composed partly of black areas where the epiphyseal cartilage remains and partly of dense white areas where fusion is proceeding."
      ]
    },
    {
      "rating": "I",
      "imageFile": "35MP_img_I.png",
      "descriptionLines": [
        "(i) Fusion of the epiphysis and metaphysis is completed. (Over the majority of its length the line of fusion has entirely disappeared, but some thickened remnant of it may still be visible.)"
      ]
    }
  ],
  "distal_phalanx_1": [
    {
      "rating": "B",
      "imageFile": "1DP_img_B.png",
      "descriptionLines": [
        "(i) The centre is just visible as a single deposit of calcium, or more rarely as multiple deposits. The border is ill-defined."
      ]
    },
    {
      "rating": "C",
      "imageFile": "1DP_img_C.png",
      "descriptionLines": [
        "(i) The centre is distinct in appearance and disc-shaped, with a smooth, continuous border."
      ]
    },
    {
      "rating": "D",
      "imageFile": "1DP_img_D.png",
      "descriptionLines": [
        "(i) The maximum diameter is half or more the width of the metaphysis."
      ]
    },
    {
      "rating": "E",
      "imageFile": "1DP_img_E.png",
      "descriptionLines": [
        "(i) The epiphysis is as wide as the metaphysis.",
        "(ii) The shape has changed, so that there is now a somewhat flattened distal border and an angulated proximal border. (The change in shape of the proximal border comes about through a downgrowth similar to that seen at this stage in the epiphysis of the middle and distal phalanges of the fingers in their central axis. Owing to the rotation of the thumb in its position on the film, however, this downgrowth appears usually at the proximomedial edge, although sometimes it may be nearly central.)"
      ]
    },
    {
      "rating": "F",
      "imageFile": "1DP_img_F.png",
      "descriptionLines": [
        "(i) The proximolateral border of the epiphysis is now concave and shapes to the head of the proximal phalanx. (In some positions of the thumb this border is not visible as such. Instead, the articular surface may be seen as a white concave line inside the proximolateral border.)",
        "(ii) On the distal border the medial and lateral surfaces can both be seen, with the base of the terminal phalanx conforming to the saddle shape between them.",
        "(iii) The epiphysis is now wider than the metaphysis."
      ]
    },
    {
      "rating": "G",
      "imageFile": "1DP_img_G.png",
      "descriptionLines": [
        "(i) The epiphysis caps the metaphysis. (Because of the position of the thumb this is better seen on the medial side.)"
      ]
    },
    {
      "rating": "H",
      "imageFile": "1DP_img_H.png",
      "descriptionLines": [
        "(i) Fusion of the epiphysis and metaphysis has begun. A line is still visible, composed partly of black areas where the epiphyseal cartilage remains, and partly of dense white areas where fusion is proceeding."
      ]
    },
    {
      "rating": "I",
      "imageFile": "1DP_img_I.png",
      "descriptionLines": [
        "(i) Fusion of the epiphysis and metaphysis is completed. (Over the majority of its length the line of fusion has entirely disappeared, but some thickened remnant of it may still be visible.)"
      ]
    }
  ],
  "distal_phalanx_3": [
    {
      "rating": "B",
      "imageFile": "35DP_img_B.png",
      "descriptionLines": [
        "(i) The centre is just visible as a single deposit of calcium, or more rarely as multiple deposits. The border is ill-defined."
      ]
    },
    {
      "rating": "C",
      "imageFile": "35DP_img_C.png",
      "descriptionLines": [
        "(i) The centre is distinct in appearance, with a smooth, continuous border."
      ]
    },
    {
      "rating": "D",
      "imageFile": "35DP_img_D.png",
      "descriptionLines": [
        "(i) The maximum diameter is half or more the width of the metaphysis."
      ]
    },
    {
      "rating": "E",
      "imageFile": "35DP_img_E.png",
      "descriptionLines": [
        "(i) The epiphysis is as wide as the metaphysis.",
        "(ii) The central portion of the proximal border has grown towards the end of the middle phalanx, so that the proximal border no longer consists of a single convex surface; no differentiation into palmar and dorsal surfaces, however, can yet be seen."
      ]
    },
    {
      "rating": "F",
      "imageFile": "35DP_img_F.png",
      "descriptionLines": [
        "(i) Palmar and dorsal proximal surfaces are distinct, and each has shaped to the trochlear articulation of the middle phalanx. The palmar surface appears as a projection proximal to the thickened white line representing the dorsal surface."
      ]
    },
    {
      "rating": "G",
      "imageFile": "35DP_img_G.png",
      "descriptionLines": [
        "(i) The epiphysis caps the metaphysis."
      ]
    },
    {
      "rating": "H",
      "imageFile": "35DP_img_H.png",
      "descriptionLines": [
        "(i) Fusion of the epiphysis and metaphysis has begun. (A line is still visible, composed partly of black areas where the epiphyseal cartilage remains and partly of dense white areas where fusion is proceeding.)"
      ]
    },
    {
      "rating": "I",
      "imageFile": "35DP_img_I.png",
      "descriptionLines": [
        "(i) Fusion of the epiphysis and metaphysis is completed. (Over the majority of its length the line of fusion has entirely disappeared, but some thickened remnant of it may still be visible.)"
      ]
    }
  ],
  "distal_phalanx_5": [
    {
      "rating": "B",
      "imageFile": "35DP_img_B.png",
      "descriptionLines": [
        "(i) The centre is just visible as a single deposit of calcium, or more rarely as multiple deposits. The border is ill-defined."
      ]
    },
    {
      "rating": "C",
      "imageFile": "35DP_img_C.png",
      "descriptionLines": [
        "(i) The centre is distinct in appearance, with a smooth, continuous border."
      ]
    },
    {
      "rating": "D",
      "imageFile": "35DP_img_D.png",
      "descriptionLines": [
        "(i) The maximum diameter is half or more the width of the metaphysis."
      ]
    },
    {
      "rating": "E",
      "imageFile": "35DP_img_E.png",
      "descriptionLines": [
        "(i) The epiphysis is as wide as the metaphysis.",
        "(ii) The central portion of the proximal border has grown towards the end of the middle phalanx, so that the proximal border no longer consists of a single convex surface; no differentiation into palmar and dorsal surfaces, however, can yet be seen."
      ]
    },
    {
      "rating": "F",
      "imageFile": "35DP_img_F.png",
      "descriptionLines": [
        "(i) Palmar and dorsal proximal surfaces are distinct, and each has shaped to the trochlear articulation of the middle phalanx. The palmar surface appears as a projection proximal to the thickened white line representing the dorsal surface."
      ]
    },
    {
      "rating": "G",
      "imageFile": "35DP_img_G.png",
      "descriptionLines": [
        "(i) The epiphysis caps the metaphysis."
      ]
    },
    {
      "rating": "H",
      "imageFile": "35DP_img_H.png",
      "descriptionLines": [
        "(i) Fusion of the epiphysis and metaphysis has begun. (A line is still visible, composed partly of black areas where the epiphyseal cartilage remains and partly of dense white areas where fusion is proceeding.)"
      ]
    },
    {
      "rating": "I",
      "imageFile": "35DP_img_I.png",
      "descriptionLines": [
        "(i) Fusion of the epiphysis and metaphysis is completed. (Over the majority of its length the line of fusion has entirely disappeared, but some thickened remnant of it may still be visible.)"
      ]
    }
  ]
};

export function getStageImagesForLandmark(landmarkId: Tw3LandmarkId): Tw3StageImageEntry[] {
  return (RAW_STAGE_MANIFEST[landmarkId] ?? []).map((row) => ({
    rating: row.rating,
    referenceSrc: stageImageUrl(row.imageFile),
    descriptionLines: row.descriptionLines,
  }));
}

export function getStageDescription(
  landmarkId: Tw3LandmarkId,
  rating: Tw3MaturityRating,
): string[] {
  const row = (RAW_STAGE_MANIFEST[landmarkId] ?? []).find((entry) => entry.rating === rating);
  return row?.descriptionLines ?? [];
}

export function getAllStageImageUrlsForLandmark(landmarkId: Tw3LandmarkId): string[] {
  return getStageImagesForLandmark(landmarkId).map((entry) => entry.referenceSrc);
}
